version: "0.1"

services:
  api-dev:
    container_name: remote_day-api
    build: ./api/
    ports:
      - "4000:4000"
    command: mix phx.server
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - GUARDIAN_SECRET_KEY="dHGoGXqwyKKpc83nKROqFoLBtIxFtsQZhw+DutWiNVui7UUTKzJB91zjFStp6DdW"
      - ENDPOINT_SECRET_KEY="i41OQYn6iYqxx4HmTt4vWQAwt0UWY80QnJwScgXXZfOPQX6AIGgPq2WyvOO7gWBwUcTKuN612zI"
    volumes:
      - './api/:/usr/src/backend'
    links:
      - db
  db:
    container_name: remote_day-db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
  react-dev:
    container_name: remote_day-react
    build: ./webapp
    volumes:
      - './webapp/:/usr/src/frontend'
    ports:
      - '3337:3000' # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=development
      - REACT_APP_TEST=yoyo
