version: "0.1"

services:
  api:
    container_name: remote_day-api
    build: ./
    ports:
      - "4000:4000"
    command: mix phoenix.server
    environment:
      - MIX_ENV=dev
      - PORT=4000
    volumes:
      - './:/usr/src/backend'
    links:
      - db
  db:
    container_name: remote_day-db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
